language: cpp

sudo: false

os:
    - linux

compiler:
    - gcc

sudo: false

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - libsdl1.2-dev
            - libsdl-image1.2-dev
            - libsdl-mixer1.2-dev
            - libsdl-ttf2.0-dev

# This doesn't build the image resources that require Inkscape.
# MEWL's makefile's "info" target is build system information, not Texinfo.

script:
    - make -j2 info mewl CPPC=g++-4.9 LD=g++-4.9
