language: cpp

sudo: false

os:
    - linux

compiler:
    - gcc

sudo: false

addons:
    apt:
        packages:
            - libsdl1.2-dev
            - libsdl-image1.2-dev
            - libsdl-mixer1.2-dev
            - libsdl-ttf2.0-dev

# This doesn't build the image resources that require Inkscape

script:
    - make info
    - make mewl -j2
